[package]
name = "askama_parser"
version.workspace = true
description = "Parser for Askama templates"
documentation = "https://docs.rs/askama"
keywords = ["markup", "template", "jinja2", "html"]
categories = ["template-engine"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition", "--cfg=docsrs"]

[[bench]]
name = "from_str"
harness = false

[[bench]]
name = "parse-complex-expression"
harness = false

[dependencies]
rustc-hash = "2.0.0"
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
unicode-ident = "1.0.12"
winnow = { version = "0.7.0", features = ["simd"] }

[dev-dependencies]
criterion = "0.8"
rand = "0.9.2"
rand_xoshiro = "0.7.0"

[features]
config = ["dep:serde", "dep:serde_derive"]
