[package]
name = "askama_macros"
version = "0.15.2"
description = "Procedural macro package for Askama"
homepage = "https://github.com/askama-rs/askama"
repository = "https://github.com/askama-rs/askama"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2024"
rust-version = "1.88"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition", "--cfg=docsrs"]

[lib]
proc-macro = true

[dependencies]
askama_derive = { package = "askama_derive", path = "../askama_derive", version = "=0.15.2", default-features = false, features = ["external-sources", "proc-macro"] }

[features]
default = ["config", "derive", "std", "urlencode"]
full = ["default", "code-in-doc", "serde_json"]

alloc = ["askama_derive/alloc"]
code-in-doc = ["askama_derive/code-in-doc"]
config = ["askama_derive/config"]
nightly-spans = ["askama_derive/nightly-spans"]
serde_json = ["askama_derive/serde_json"]
std = ["askama_derive/std"]
urlencode = ["askama_derive/urlencode"]

# Unused, but we want to have the same features as `askama`.
derive = []
