[package]
name = "make-buffer-write_token_str"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.93"

[dependencies]
bitmaps = "3.2.1"
itertools = "0.14.0"
rayon = "1.11.0"

[workspace]
members = ["."]
