[book]
authors = ["askama-rs developers"]
language = "en"
src = "src"
title = "Askama"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/askama-rs/askama/tree/master/book"
edit-url-template = "https://github.com/askama-rs/askama/tree/master/book/{path}"
playground.runnable = false
